// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: New Button Testing

#ifndef _NEW_BUTTON_TESTING_UI_H
#define _NEW_BUTTON_TESTING_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen_1.h"
#include "ui_Screen_2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_white_blank_png);    // assets/White Blank.png
LV_IMG_DECLARE(ui_img_setpoint_up_png);    // assets/Setpoint UP.png
LV_IMG_DECLARE(ui_img_setpoint_down_png);    // assets/Setpoint Down.png
LV_IMG_DECLARE(
    ui_img_1471738535);    // assets/png-clipart-computer-icons-fan-ventilation-fan-technic-monochrome-thumbnail.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
