// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: New Button Testing

#include "ui.h"

lv_obj_t * uic_Fan_On;
lv_obj_t * uic_Ideal_Temp_Value;
lv_obj_t * uic_MAX_FAN;
lv_obj_t * uic_Ideal_Temp_Down;
lv_obj_t * uic_Ideal_Temp_Up;
lv_obj_t * uic_House_Humidity_symbol;
lv_obj_t * uic_Roof_Humidity_symbol;
lv_obj_t * uic_House_Temp_symbol;
lv_obj_t * uic_Roof_Temp_symbol;
lv_obj_t * uic_Fan_Speed_Slider;
lv_obj_t * uic_Ideal_Temp_Name;
lv_obj_t * uic_Max_Fan_Text;
lv_obj_t * uic_Fan_Speed_Value;
lv_obj_t * uic_House_Temp_Value;
lv_obj_t * uic_House_Humidity_Value;
lv_obj_t * uic_Roof_Humidity_Value;
lv_obj_t * uic_Roof_Temp_Value;
lv_obj_t * uic_Menu;
lv_obj_t * uic_Menu_Lable;
lv_obj_t * uic_Clock_Value;
lv_obj_t * uic_ON_;
lv_obj_t * uic_On_Off;
lv_obj_t * uic_Screen_1;
lv_obj_t * ui_Screen_1 = NULL;
lv_obj_t * ui_On_Off = NULL;
lv_obj_t * ui_ON_ = NULL;
lv_obj_t * ui_Clock_Value = NULL;
lv_obj_t * ui_Menu_Lable = NULL;
lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_Roof_Temp_Value = NULL;
lv_obj_t * ui_Roof_Humidity_Value = NULL;
lv_obj_t * ui_House_Humidity_Value = NULL;
lv_obj_t * ui_House_Temp_Value = NULL;
lv_obj_t * ui_Fan_Speed_Value = NULL;
lv_obj_t * ui_Max_Fan_Text_ = NULL;
lv_obj_t * ui_Ideal_Temp_Name = NULL;
lv_obj_t * ui_Fan_Speed_Slider = NULL;
lv_obj_t * ui_Roof_Temp_symbol = NULL;
lv_obj_t * ui_House_Temp_symbol = NULL;
lv_obj_t * ui_Roof_Humidity_symbol = NULL;
lv_obj_t * ui_House_Humidity_symbol = NULL;
lv_obj_t * ui_Ideal_Temp_Up = NULL;
lv_obj_t * ui_Ideal_Temp_Down = NULL;
lv_obj_t * ui_MAX_FAN = NULL;
lv_obj_t * ui_Ideal_Temp_Value = NULL;
lv_obj_t * ui_Fan_On = NULL;
// event funtions
void ui_event_On_Off(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_On_Off, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        _ui_checked_set_text_value(ui_ON_, target, "Off", "On");
    }
}

void ui_event_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Menu, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        _ui_screen_change(&ui_Screen_2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_2_screen_init);
    }
}

void ui_event_Fan_Speed_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Fan_Speed_Value, target, "", "");
    }
}

void ui_event_Ideal_Temp_Up(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Ideal_Temp_Value, 1);
    }
}

void ui_event_Ideal_Temp_Down(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Ideal_Temp_Value, -1);
    }
}

void ui_event_MAX_FAN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_MAX_FAN, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        _ui_slider_increment(ui_Fan_Speed_Slider, 100, LV_ANIM_ON);
    }
}

// build funtions

void ui_Screen_1_screen_init(void)
{
    ui_Screen_1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen_1, &ui_img_white_blank_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_On_Off = lv_btn_create(ui_Screen_1);
    lv_obj_set_width(ui_On_Off, 61);
    lv_obj_set_height(ui_On_Off, 52);
    lv_obj_set_x(ui_On_Off, -82);
    lv_obj_set_y(ui_On_Off, -127);
    lv_obj_set_align(ui_On_Off, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_On_Off, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_On_Off, lv_color_hex(0x27F117), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_On_Off, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_On_Off, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_On_Off, lv_color_hex(0xED0D0D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_On_Off, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ON_ = lv_label_create(ui_On_Off);
    lv_obj_set_width(ui_ON_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ON_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ON_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ON_, "On");

    ui_Clock_Value = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Clock_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock_Value, 2);
    lv_obj_set_y(ui_Clock_Value, -137);
    lv_obj_set_align(ui_Clock_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clock_Value, "12:00 am");
    lv_obj_clear_flag(ui_Clock_Value, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_letter_space(ui_Clock_Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Clock_Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Lable = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Menu_Lable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu_Lable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Menu_Lable, 81);
    lv_obj_set_y(ui_Menu_Lable, -134);
    lv_obj_set_align(ui_Menu_Lable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu_Lable, "Menu");
    lv_obj_clear_flag(ui_Menu_Lable, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Menu_Lable, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu = lv_obj_create(ui_Screen_1);
    lv_obj_remove_style_all(ui_Menu);
    lv_obj_set_width(ui_Menu, 62);
    lv_obj_set_height(ui_Menu, 39);
    lv_obj_set_x(ui_Menu, 81);
    lv_obj_set_y(ui_Menu, -134);
    lv_obj_set_align(ui_Menu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Menu, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Menu, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu, lv_color_hex(0xF21212), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Menu, 50, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Roof_Temp_Value = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Roof_Temp_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roof_Temp_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roof_Temp_Value, -22);
    lv_obj_set_y(ui_Roof_Temp_Value, -42);
    lv_obj_set_align(ui_Roof_Temp_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Roof_Temp_Value, "00");

    ui_Roof_Humidity_Value = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Roof_Humidity_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roof_Humidity_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roof_Humidity_Value, 19);
    lv_obj_set_y(ui_Roof_Humidity_Value, -42);
    lv_obj_set_align(ui_Roof_Humidity_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Roof_Humidity_Value, "00");

    ui_House_Humidity_Value = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_House_Humidity_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_House_Humidity_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_House_Humidity_Value, 19);
    lv_obj_set_y(ui_House_Humidity_Value, 7);
    lv_obj_set_align(ui_House_Humidity_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_House_Humidity_Value, "00");

    ui_House_Temp_Value = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_House_Temp_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_House_Temp_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_House_Temp_Value, -22);
    lv_obj_set_y(ui_House_Temp_Value, 7);
    lv_obj_set_align(ui_House_Temp_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_House_Temp_Value, "00");

    ui_Fan_Speed_Value = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Fan_Speed_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fan_Speed_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fan_Speed_Value, -101);
    lv_obj_set_y(ui_Fan_Speed_Value, 47);
    lv_obj_set_align(ui_Fan_Speed_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan_Speed_Value, "00");

    ui_Max_Fan_Text_ = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Max_Fan_Text_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Max_Fan_Text_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Max_Fan_Text_, 91);
    lv_obj_set_y(ui_Max_Fan_Text_, 134);
    lv_obj_set_align(ui_Max_Fan_Text_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Max_Fan_Text_, "FAN\nMAX");

    ui_Ideal_Temp_Name = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Ideal_Temp_Name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ideal_Temp_Name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ideal_Temp_Name, -31);
    lv_obj_set_y(ui_Ideal_Temp_Name, 147);
    lv_obj_set_align(ui_Ideal_Temp_Name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ideal_Temp_Name, "IDEAL TEMP");
    lv_obj_set_style_text_color(ui_Ideal_Temp_Name, lv_color_hex(0xF50707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ideal_Temp_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Ideal_Temp_Name, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Ideal_Temp_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ideal_Temp_Name, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan_Speed_Slider = lv_slider_create(ui_Screen_1);
    lv_slider_set_value(ui_Fan_Speed_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Fan_Speed_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Fan_Speed_Slider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_Fan_Speed_Slider, 150);
    lv_obj_set_height(ui_Fan_Speed_Slider, 10);
    lv_obj_set_x(ui_Fan_Speed_Slider, 5);
    lv_obj_set_y(ui_Fan_Speed_Slider, 90);
    lv_obj_set_align(ui_Fan_Speed_Slider, LV_ALIGN_CENTER);

    ui_Roof_Temp_symbol = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Roof_Temp_symbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roof_Temp_symbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roof_Temp_symbol, -22);
    lv_obj_set_y(ui_Roof_Temp_symbol, -25);
    lv_obj_set_align(ui_Roof_Temp_symbol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Roof_Temp_symbol, "°C");
    lv_obj_set_style_text_font(ui_Roof_Temp_symbol, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_House_Temp_symbol = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_House_Temp_symbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_House_Temp_symbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_House_Temp_symbol, -22);
    lv_obj_set_y(ui_House_Temp_symbol, 24);
    lv_obj_set_align(ui_House_Temp_symbol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_House_Temp_symbol, "°C");
    lv_obj_set_style_text_font(ui_House_Temp_symbol, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roof_Humidity_symbol = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_Roof_Humidity_symbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roof_Humidity_symbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roof_Humidity_symbol, 19);
    lv_obj_set_y(ui_Roof_Humidity_symbol, -25);
    lv_obj_set_align(ui_Roof_Humidity_symbol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Roof_Humidity_symbol, "%");
    lv_obj_set_style_text_font(ui_Roof_Humidity_symbol, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_House_Humidity_symbol = lv_label_create(ui_Screen_1);
    lv_obj_set_width(ui_House_Humidity_symbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_House_Humidity_symbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_House_Humidity_symbol, 19);
    lv_obj_set_y(ui_House_Humidity_symbol, 24);
    lv_obj_set_align(ui_House_Humidity_symbol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_House_Humidity_symbol, "%");
    lv_obj_set_style_text_font(ui_House_Humidity_symbol, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ideal_Temp_Up = lv_obj_create(ui_Screen_1);
    lv_obj_remove_style_all(ui_Ideal_Temp_Up);
    lv_obj_set_width(ui_Ideal_Temp_Up, 45);
    lv_obj_set_height(ui_Ideal_Temp_Up, 77);
    lv_obj_set_x(ui_Ideal_Temp_Up, -90);
    lv_obj_set_y(ui_Ideal_Temp_Up, 149);
    lv_obj_set_align(ui_Ideal_Temp_Up, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ideal_Temp_Up, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ideal_Temp_Up, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_img_src(ui_Ideal_Temp_Up, &ui_img_setpoint_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ideal_Temp_Down = lv_obj_create(ui_Screen_1);
    lv_obj_remove_style_all(ui_Ideal_Temp_Down);
    lv_obj_set_width(ui_Ideal_Temp_Down, 42);
    lv_obj_set_height(ui_Ideal_Temp_Down, 75);
    lv_obj_set_x(ui_Ideal_Temp_Down, 31);
    lv_obj_set_y(ui_Ideal_Temp_Down, 149);
    lv_obj_set_align(ui_Ideal_Temp_Down, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ideal_Temp_Down, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Ideal_Temp_Down,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_img_src(ui_Ideal_Temp_Down, &ui_img_setpoint_down_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MAX_FAN = lv_obj_create(ui_Screen_1);
    lv_obj_remove_style_all(ui_MAX_FAN);
    lv_obj_set_width(ui_MAX_FAN, 47);
    lv_obj_set_height(ui_MAX_FAN, 43);
    lv_obj_set_x(ui_MAX_FAN, 90);
    lv_obj_set_y(ui_MAX_FAN, 133);
    lv_obj_set_align(ui_MAX_FAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MAX_FAN, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_MAX_FAN, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_MAX_FAN, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MAX_FAN, lv_color_hex(0xF21212), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MAX_FAN, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_MAX_FAN, 50, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Ideal_Temp_Value = lv_spinbox_create(ui_Screen_1);
    lv_obj_set_width(ui_Ideal_Temp_Value, 38);
    lv_obj_set_height(ui_Ideal_Temp_Value, 34);
    lv_obj_set_x(ui_Ideal_Temp_Value, -30);
    lv_obj_set_y(ui_Ideal_Temp_Value, 128);
    lv_obj_set_align(ui_Ideal_Temp_Value, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Ideal_Temp_Value,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_spinbox_set_digit_format(ui_Ideal_Temp_Value, 2, 0);
    lv_spinbox_set_range(ui_Ideal_Temp_Value, 10, 40);
    lv_spinbox_set_cursor_pos(ui_Ideal_Temp_Value, 1 - 1);
    lv_spinbox_set_value(ui_Ideal_Temp_Value, 10);

    ui_Fan_On = lv_spinner_create(ui_Screen_1, 1000, 90);
    lv_obj_set_width(ui_Fan_On, 26);
    lv_obj_set_height(ui_Fan_On, 22);
    lv_obj_set_x(ui_Fan_On, -100);
    lv_obj_set_y(ui_Fan_On, 71);
    lv_obj_set_align(ui_Fan_On, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Fan_On, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Fan_On, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Fan_On, lv_color_hex(0x1AD2E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Fan_On, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Fan_On, &ui_img_1471738535, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Fan_On, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Fan_On, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Fan_On, &ui_img_1471738535, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_On_Off, ui_event_On_Off, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Menu, ui_event_Menu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Fan_Speed_Slider, ui_event_Fan_Speed_Slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ideal_Temp_Up, ui_event_Ideal_Temp_Up, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ideal_Temp_Down, ui_event_Ideal_Temp_Down, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MAX_FAN, ui_event_MAX_FAN, LV_EVENT_ALL, NULL);
    uic_Screen_1 = ui_Screen_1;
    uic_On_Off = ui_On_Off;
    uic_ON_ = ui_ON_;
    uic_Clock_Value = ui_Clock_Value;
    uic_Menu_Lable = ui_Menu_Lable;
    uic_Menu = ui_Menu;
    uic_Roof_Temp_Value = ui_Roof_Temp_Value;
    uic_Roof_Humidity_Value = ui_Roof_Humidity_Value;
    uic_House_Humidity_Value = ui_House_Humidity_Value;
    uic_House_Temp_Value = ui_House_Temp_Value;
    uic_Fan_Speed_Value = ui_Fan_Speed_Value;
    uic_Max_Fan_Text = ui_Max_Fan_Text_;
    uic_Ideal_Temp_Name = ui_Ideal_Temp_Name;
    uic_Fan_Speed_Slider = ui_Fan_Speed_Slider;
    uic_Roof_Temp_symbol = ui_Roof_Temp_symbol;
    uic_House_Temp_symbol = ui_House_Temp_symbol;
    uic_Roof_Humidity_symbol = ui_Roof_Humidity_symbol;
    uic_House_Humidity_symbol = ui_House_Humidity_symbol;
    uic_Ideal_Temp_Up = ui_Ideal_Temp_Up;
    uic_Ideal_Temp_Down = ui_Ideal_Temp_Down;
    uic_MAX_FAN = ui_MAX_FAN;
    uic_Ideal_Temp_Value = ui_Ideal_Temp_Value;
    uic_Fan_On = ui_Fan_On;

}

void ui_Screen_1_screen_destroy(void)
{
    if(ui_Screen_1) lv_obj_del(ui_Screen_1);

    // NULL screen variables
    uic_Screen_1 = NULL;
    ui_Screen_1 = NULL;
    uic_On_Off = NULL;
    ui_On_Off = NULL;
    uic_ON_ = NULL;
    ui_ON_ = NULL;
    uic_Clock_Value = NULL;
    ui_Clock_Value = NULL;
    uic_Menu_Lable = NULL;
    ui_Menu_Lable = NULL;
    uic_Menu = NULL;
    ui_Menu = NULL;
    uic_Roof_Temp_Value = NULL;
    ui_Roof_Temp_Value = NULL;
    uic_Roof_Humidity_Value = NULL;
    ui_Roof_Humidity_Value = NULL;
    uic_House_Humidity_Value = NULL;
    ui_House_Humidity_Value = NULL;
    uic_House_Temp_Value = NULL;
    ui_House_Temp_Value = NULL;
    uic_Fan_Speed_Value = NULL;
    ui_Fan_Speed_Value = NULL;
    uic_Max_Fan_Text = NULL;
    ui_Max_Fan_Text_ = NULL;
    uic_Ideal_Temp_Name = NULL;
    ui_Ideal_Temp_Name = NULL;
    uic_Fan_Speed_Slider = NULL;
    ui_Fan_Speed_Slider = NULL;
    uic_Roof_Temp_symbol = NULL;
    ui_Roof_Temp_symbol = NULL;
    uic_House_Temp_symbol = NULL;
    ui_House_Temp_symbol = NULL;
    uic_Roof_Humidity_symbol = NULL;
    ui_Roof_Humidity_symbol = NULL;
    uic_House_Humidity_symbol = NULL;
    ui_House_Humidity_symbol = NULL;
    uic_Ideal_Temp_Up = NULL;
    ui_Ideal_Temp_Up = NULL;
    uic_Ideal_Temp_Down = NULL;
    ui_Ideal_Temp_Down = NULL;
    uic_MAX_FAN = NULL;
    ui_MAX_FAN = NULL;
    uic_Ideal_Temp_Value = NULL;
    ui_Ideal_Temp_Value = NULL;
    uic_Fan_On = NULL;
    ui_Fan_On = NULL;

}
