// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: New Button Testing

#ifndef UI_SCREEN_2_H
#define UI_SCREEN_2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_2
extern void ui_Screen_2_screen_init(void);
extern void ui_Screen_2_screen_destroy(void);
extern lv_obj_t * ui_Screen_2;
extern void ui_event_Menu_Screen_2(lv_event_t * e);
extern lv_obj_t * ui_Menu_Screen_2;
extern lv_obj_t * ui_Menu_Lable_Screen_2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen_2;
extern lv_obj_t * uic_Menu_Screen_2;
extern lv_obj_t * uic_Menu_Lable_Screen_2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

