// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: New Button Testing

#ifndef UI_SCREEN_1_H
#define UI_SCREEN_1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_1
extern void ui_Screen_1_screen_init(void);
extern void ui_Screen_1_screen_destroy(void);
extern lv_obj_t * ui_Screen_1;
extern void ui_event_On_Off(lv_event_t * e);
extern lv_obj_t * ui_On_Off;
extern lv_obj_t * ui_ON_;
extern lv_obj_t * ui_Clock_Value;
extern lv_obj_t * ui_Menu_Lable;
extern void ui_event_Menu(lv_event_t * e);
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_Roof_Temp_Value;
extern lv_obj_t * ui_Roof_Humidity_Value;
extern lv_obj_t * ui_House_Humidity_Value;
extern lv_obj_t * ui_House_Temp_Value;
extern lv_obj_t * ui_Fan_Speed_Value;
extern lv_obj_t * ui_Max_Fan_Text_;
extern lv_obj_t * ui_Ideal_Temp_Name;
extern void ui_event_Fan_Speed_Slider(lv_event_t * e);
extern lv_obj_t * ui_Fan_Speed_Slider;
extern lv_obj_t * ui_Roof_Temp_symbol;
extern lv_obj_t * ui_House_Temp_symbol;
extern lv_obj_t * ui_Roof_Humidity_symbol;
extern lv_obj_t * ui_House_Humidity_symbol;
extern void ui_event_Ideal_Temp_Up(lv_event_t * e);
extern lv_obj_t * ui_Ideal_Temp_Up;
extern void ui_event_Ideal_Temp_Down(lv_event_t * e);
extern lv_obj_t * ui_Ideal_Temp_Down;
extern void ui_event_MAX_FAN(lv_event_t * e);
extern lv_obj_t * ui_MAX_FAN;
extern lv_obj_t * ui_Ideal_Temp_Value;
extern lv_obj_t * ui_Fan_On;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen_1;
extern lv_obj_t * uic_On_Off;
extern lv_obj_t * uic_ON_;
extern lv_obj_t * uic_Clock_Value;
extern lv_obj_t * uic_Menu_Lable;
extern lv_obj_t * uic_Menu;
extern lv_obj_t * uic_Roof_Temp_Value;
extern lv_obj_t * uic_Roof_Humidity_Value;
extern lv_obj_t * uic_House_Humidity_Value;
extern lv_obj_t * uic_House_Temp_Value;
extern lv_obj_t * uic_Fan_Speed_Value;
extern lv_obj_t * uic_Max_Fan_Text;
extern lv_obj_t * uic_Ideal_Temp_Name;
extern lv_obj_t * uic_Fan_Speed_Slider;
extern lv_obj_t * uic_Roof_Temp_symbol;
extern lv_obj_t * uic_House_Temp_symbol;
extern lv_obj_t * uic_Roof_Humidity_symbol;
extern lv_obj_t * uic_House_Humidity_symbol;
extern lv_obj_t * uic_Ideal_Temp_Up;
extern lv_obj_t * uic_Ideal_Temp_Down;
extern lv_obj_t * uic_MAX_FAN;
extern lv_obj_t * uic_Ideal_Temp_Value;
extern lv_obj_t * uic_Fan_On;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

