// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Power

lv_obj_t * ui_Power_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Power;
    cui_Power = lv_imgbtn_create(comp_parent);
    lv_obj_set_width(cui_Power, 53);
    lv_obj_set_height(cui_Power, 53);
    lv_obj_set_x(cui_Power, -75);
    lv_obj_set_y(cui_Power, -121);
    lv_obj_set_align(cui_Power, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Power, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(cui_Power, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_img_opa(cui_Power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(cui_Power, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_POWER_NUM);
    children[UI_COMP_POWER_POWER] = cui_Power;
    lv_obj_add_event_cb(cui_Power, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Power, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Power_create_hook(cui_Power);
    return cui_Power;
}

