// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Fan_Speed_Slider;
lv_obj_t * uic_Ideal_Temp_Value;
lv_obj_t * uic_Ideal_Temp_Panel;
lv_obj_t * uic_Ideal_Temp_Slider;
lv_obj_t * uic_Filter_Life_Value;
lv_obj_t * uic_Filter_Life_Lable;
lv_obj_t * uic_Filter_Life_panel;
lv_obj_t * uic_Roof_Humidity_Value;
lv_obj_t * uic_Roof_Temp_Value;
lv_obj_t * uic_House_Humidity_Value;
lv_obj_t * uic_House_Temp_Value;
lv_obj_t * uic_House_Humidity_Symbol;
lv_obj_t * uic_House_Humidity_Panel;
lv_obj_t * uic_House_Temp_Panel;
lv_obj_t * uic_Roof_Humidity_Symbol;
lv_obj_t * uic_Roof_Temp_Symbol;
lv_obj_t * uic_Roof_Temp_Panel;
lv_obj_t * uic_Roof_Humidity_Panel;
lv_obj_t * uic_Fan_Speed_Value;
lv_obj_t * uic_Ideal_Temp_lable;
lv_obj_t * uic_Time_Value;
lv_obj_t * uic_Time_Panel;
lv_obj_t * uic_Setpoint_Up;
lv_obj_t * uic_Setpoint_Down;
lv_obj_t * uic_Burnt_Toast;
lv_obj_t * uic_Menu;
lv_obj_t * uic_Power;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Power = NULL;
lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_Burnt_Toast = NULL;
lv_obj_t * ui_Setpoint_Down = NULL;
lv_obj_t * ui_Setpoint_Up = NULL;
lv_obj_t * ui_Time_Panel = NULL;
lv_obj_t * ui_Time_Value = NULL;
lv_obj_t * ui_Ideal_Temp_lable = NULL;
lv_obj_t * ui_Fan_Speed_Panel = NULL;
lv_obj_t * ui_Fan_Speed_Lable = NULL;
lv_obj_t * ui_Fan_Speed_Value = NULL;
lv_obj_t * ui_Roof_Humidity_Panel = NULL;
lv_obj_t * ui_Roof_Temp_Panel = NULL;
lv_obj_t * ui_Roof_Temp_Symbol = NULL;
lv_obj_t * ui_Roof_Humidity_Symbol = NULL;
lv_obj_t * ui_House_Temp_Panel = NULL;
lv_obj_t * ui_House_Humidity_Panel = NULL;
lv_obj_t * ui_House_Temp_Symbol = NULL;
lv_obj_t * ui_House_Humidity_Symbol = NULL;
lv_obj_t * ui_House_Temp_Value = NULL;
lv_obj_t * ui_House_Humidity_Value = NULL;
lv_obj_t * ui_Roof_Temp_Value = NULL;
lv_obj_t * ui_Roof_Humidity_Value = NULL;
lv_obj_t * ui_Filter_Life_panel = NULL;
lv_obj_t * ui_Filter_Life_Lable = NULL;
lv_obj_t * ui_Filter_Life_Value = NULL;
lv_obj_t * ui_Ideal_Temp_Slider = NULL;
lv_obj_t * ui_Ideal_Temp_Panel = NULL;
lv_obj_t * ui_Ideal_Temp_Value = NULL;
lv_obj_t * ui_Fan_Speed_Slider = NULL;
// event funtions
void ui_event_Setpoint_Down(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_increment(ui_Ideal_Temp_Slider, -1, LV_ANIM_ON);
    }
}

void ui_event_Setpoint_Up(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_increment(ui_Ideal_Temp_Slider, 1, LV_ANIM_ON);
    }
}

void ui_event_Ideal_Temp_Slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Ideal_Temp_Value, target, "", "");
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_touchscreen_bg_240x320_16bit_rounded_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Screen1, lv_color_hex(0x1B22A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Screen1, lv_color_hex(0xF51515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Screen1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x3D0808), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Screen1, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Power = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Power, 58);
    lv_obj_set_height(ui_Power, 48);
    lv_obj_set_x(ui_Power, -79);
    lv_obj_set_y(ui_Power, -126);
    lv_obj_set_align(ui_Power, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Power, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Power, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Power, lv_color_hex(0x2D35D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Power, lv_color_hex(0xF90C0C), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Power, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Power, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Power, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Power, 180, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Power, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Menu = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Menu, 60);
    lv_obj_set_height(ui_Menu, 45);
    lv_obj_set_x(ui_Menu, 84);
    lv_obj_set_y(ui_Menu, -131);
    lv_obj_set_align(ui_Menu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Menu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Menu, lv_color_hex(0x1D40E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Menu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Menu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Menu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu, lv_color_hex(0x651D1D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Menu, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Menu, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Burnt_Toast = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Burnt_Toast, 50);
    lv_obj_set_height(ui_Burnt_Toast, 50);
    lv_obj_set_x(ui_Burnt_Toast, 90);
    lv_obj_set_y(ui_Burnt_Toast, 126);
    lv_obj_set_align(ui_Burnt_Toast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Burnt_Toast, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Burnt_Toast, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Burnt_Toast, lv_color_hex(0x2E46CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Burnt_Toast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Burnt_Toast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Burnt_Toast, lv_color_hex(0xEB1414), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Burnt_Toast, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_Burnt_Toast, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_Burnt_Toast, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Burnt_Toast, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Burnt_Toast, 180, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Burnt_Toast, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Setpoint_Down = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Setpoint_Down, 48);
    lv_obj_set_height(ui_Setpoint_Down, 33);
    lv_obj_set_x(ui_Setpoint_Down, 32);
    lv_obj_set_y(ui_Setpoint_Down, 118);
    lv_obj_set_align(ui_Setpoint_Down, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setpoint_Down, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Setpoint_Down, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Setpoint_Down, lv_color_hex(0x2624E9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setpoint_Down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setpoint_Down, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setpoint_Down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Setpoint_Down, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Setpoint_Down, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setpoint_Down, lv_color_hex(0x651D1D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Setpoint_Down, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Setpoint_Down, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Setpoint_Down, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Setpoint_Up = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Setpoint_Up, 47);
    lv_obj_set_height(ui_Setpoint_Up, 33);
    lv_obj_set_x(ui_Setpoint_Up, -80);
    lv_obj_set_y(ui_Setpoint_Up, 131);
    lv_obj_set_align(ui_Setpoint_Up, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setpoint_Up, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Setpoint_Up, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Setpoint_Up, lv_color_hex(0xD62D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setpoint_Up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setpoint_Up, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setpoint_Up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Setpoint_Up, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Setpoint_Up, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setpoint_Up, lv_color_hex(0x651D1D), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Setpoint_Up, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Setpoint_Up, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Setpoint_Up, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Time_Panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Time_Panel, 56);
    lv_obj_set_height(ui_Time_Panel, 22);
    lv_obj_set_x(ui_Time_Panel, 1);
    lv_obj_set_y(ui_Time_Panel, -140);
    lv_obj_set_align(ui_Time_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Time_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Time_Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Time_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Value, 0);
    lv_obj_set_y(ui_Time_Value, -140);
    lv_obj_set_align(ui_Time_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time_Value, "00:00");
    lv_obj_set_style_text_color(ui_Time_Value, lv_color_hex(0x090000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ideal_Temp_lable = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Ideal_Temp_lable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ideal_Temp_lable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ideal_Temp_lable, -23);
    lv_obj_set_y(ui_Ideal_Temp_lable, 137);
    lv_obj_set_align(ui_Ideal_Temp_lable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ideal_Temp_lable, "Ideal\nTemp");
    lv_obj_set_style_text_color(ui_Ideal_Temp_lable, lv_color_hex(0x141111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Ideal_Temp_lable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Ideal_Temp_lable, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Ideal_Temp_lable, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Ideal_Temp_lable, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan_Speed_Panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Fan_Speed_Panel, 34);
    lv_obj_set_height(ui_Fan_Speed_Panel, 20);
    lv_obj_set_x(ui_Fan_Speed_Panel, 55);
    lv_obj_set_y(ui_Fan_Speed_Panel, 66);
    lv_obj_set_align(ui_Fan_Speed_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Fan_Speed_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Fan_Speed_Lable = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Fan_Speed_Lable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fan_Speed_Lable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fan_Speed_Lable, -13);
    lv_obj_set_y(ui_Fan_Speed_Lable, 50);
    lv_obj_set_align(ui_Fan_Speed_Lable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan_Speed_Lable, "FAN%");
    lv_obj_set_style_text_color(ui_Fan_Speed_Lable, lv_color_hex(0x040000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fan_Speed_Lable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan_Speed_Lable, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fan_Speed_Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Fan_Speed_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fan_Speed_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fan_Speed_Value, 54);
    lv_obj_set_y(ui_Fan_Speed_Value, 66);
    lv_obj_set_align(ui_Fan_Speed_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fan_Speed_Value, "00");
    lv_obj_set_style_text_color(ui_Fan_Speed_Value, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fan_Speed_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fan_Speed_Value, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roof_Humidity_Panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Roof_Humidity_Panel, 28);
    lv_obj_set_height(ui_Roof_Humidity_Panel, 20);
    lv_obj_set_x(ui_Roof_Humidity_Panel, 17);
    lv_obj_set_y(ui_Roof_Humidity_Panel, -41);
    lv_obj_set_align(ui_Roof_Humidity_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Roof_Humidity_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roof_Temp_Panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Roof_Temp_Panel, 28);
    lv_obj_set_height(ui_Roof_Temp_Panel, 20);
    lv_obj_set_x(ui_Roof_Temp_Panel, -11);
    lv_obj_set_y(ui_Roof_Temp_Panel, -41);
    lv_obj_set_align(ui_Roof_Temp_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Roof_Temp_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roof_Temp_Symbol = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Roof_Temp_Symbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roof_Temp_Symbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roof_Temp_Symbol, -12);
    lv_obj_set_y(ui_Roof_Temp_Symbol, -24);
    lv_obj_set_align(ui_Roof_Temp_Symbol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Roof_Temp_Symbol, "°C");
    lv_obj_set_style_text_color(ui_Roof_Temp_Symbol, lv_color_hex(0x1B0CE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roof_Temp_Symbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roof_Temp_Symbol, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roof_Humidity_Symbol = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Roof_Humidity_Symbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roof_Humidity_Symbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roof_Humidity_Symbol, 17);
    lv_obj_set_y(ui_Roof_Humidity_Symbol, -24);
    lv_obj_set_align(ui_Roof_Humidity_Symbol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Roof_Humidity_Symbol, "%");
    lv_obj_set_style_text_color(ui_Roof_Humidity_Symbol, lv_color_hex(0x0D18EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roof_Humidity_Symbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roof_Humidity_Symbol, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_House_Temp_Panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_House_Temp_Panel, 38);
    lv_obj_set_height(ui_House_Temp_Panel, 26);
    lv_obj_set_x(ui_House_Temp_Panel, -49);
    lv_obj_set_y(ui_House_Temp_Panel, 19);
    lv_obj_set_align(ui_House_Temp_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_House_Temp_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_House_Humidity_Panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_House_Humidity_Panel, 38);
    lv_obj_set_height(ui_House_Humidity_Panel, 26);
    lv_obj_set_x(ui_House_Humidity_Panel, 55);
    lv_obj_set_y(ui_House_Humidity_Panel, 17);
    lv_obj_set_align(ui_House_Humidity_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_House_Humidity_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_House_Temp_Symbol = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_House_Temp_Symbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_House_Temp_Symbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_House_Temp_Symbol, -50);
    lv_obj_set_y(ui_House_Temp_Symbol, 38);
    lv_obj_set_align(ui_House_Temp_Symbol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_House_Temp_Symbol, "°C");
    lv_obj_set_style_text_color(ui_House_Temp_Symbol, lv_color_hex(0x1B0CE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_House_Temp_Symbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_House_Temp_Symbol, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_House_Humidity_Symbol = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_House_Humidity_Symbol, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_House_Humidity_Symbol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_House_Humidity_Symbol, 54);
    lv_obj_set_y(ui_House_Humidity_Symbol, 37);
    lv_obj_set_align(ui_House_Humidity_Symbol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_House_Humidity_Symbol, "%");
    lv_obj_set_style_text_color(ui_House_Humidity_Symbol, lv_color_hex(0x0D18EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_House_Humidity_Symbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_House_Humidity_Symbol, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_House_Temp_Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_House_Temp_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_House_Temp_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_House_Temp_Value, -50);
    lv_obj_set_y(ui_House_Temp_Value, 19);
    lv_obj_set_align(ui_House_Temp_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_House_Temp_Value, "00");
    lv_obj_set_style_text_color(ui_House_Temp_Value, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_House_Temp_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_House_Temp_Value, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_House_Humidity_Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_House_Humidity_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_House_Humidity_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_House_Humidity_Value, 54);
    lv_obj_set_y(ui_House_Humidity_Value, 17);
    lv_obj_set_align(ui_House_Humidity_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_House_Humidity_Value, "00");
    lv_obj_set_style_text_color(ui_House_Humidity_Value, lv_color_hex(0x040000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_House_Humidity_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_House_Humidity_Value, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roof_Temp_Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Roof_Temp_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roof_Temp_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roof_Temp_Value, -11);
    lv_obj_set_y(ui_Roof_Temp_Value, -42);
    lv_obj_set_align(ui_Roof_Temp_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Roof_Temp_Value, "00");
    lv_obj_set_style_text_color(ui_Roof_Temp_Value, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roof_Temp_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roof_Temp_Value, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roof_Humidity_Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Roof_Humidity_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roof_Humidity_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roof_Humidity_Value, 16);
    lv_obj_set_y(ui_Roof_Humidity_Value, -42);
    lv_obj_set_align(ui_Roof_Humidity_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Roof_Humidity_Value, "00");
    lv_obj_set_style_text_color(ui_Roof_Humidity_Value, lv_color_hex(0x040000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roof_Humidity_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roof_Humidity_Value, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Filter_Life_panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Filter_Life_panel, 34);
    lv_obj_set_height(ui_Filter_Life_panel, 20);
    lv_obj_set_x(ui_Filter_Life_panel, 99);
    lv_obj_set_y(ui_Filter_Life_panel, -38);
    lv_obj_set_align(ui_Filter_Life_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Filter_Life_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Filter_Life_Lable = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Filter_Life_Lable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Filter_Life_Lable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Filter_Life_Lable, 99);
    lv_obj_set_y(ui_Filter_Life_Lable, -57);
    lv_obj_set_align(ui_Filter_Life_Lable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Filter_Life_Lable, "Filter");
    lv_obj_set_style_text_color(ui_Filter_Life_Lable, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Filter_Life_Lable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Filter_Life_Lable, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Filter_Life_Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Filter_Life_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Filter_Life_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Filter_Life_Value, 99);
    lv_obj_set_y(ui_Filter_Life_Value, -38);
    lv_obj_set_align(ui_Filter_Life_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Filter_Life_Value, "OK");
    lv_obj_set_style_text_color(ui_Filter_Life_Value, lv_color_hex(0x1C9718), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Filter_Life_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Filter_Life_Value, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ideal_Temp_Slider = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Ideal_Temp_Slider, 10, 34);
    lv_slider_set_value(ui_Ideal_Temp_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Ideal_Temp_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Ideal_Temp_Slider, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_Ideal_Temp_Slider, 74);
    lv_obj_set_height(ui_Ideal_Temp_Slider, 14);
    lv_obj_set_x(ui_Ideal_Temp_Slider, -4);
    lv_obj_set_y(ui_Ideal_Temp_Slider, 173);
    lv_obj_set_align(ui_Ideal_Temp_Slider, LV_ALIGN_CENTER);
    lv_obj_set_style_opa(ui_Ideal_Temp_Slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ideal_Temp_Panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Ideal_Temp_Panel, 40);
    lv_obj_set_height(ui_Ideal_Temp_Panel, 22);
    lv_obj_set_x(ui_Ideal_Temp_Panel, -24);
    lv_obj_set_y(ui_Ideal_Temp_Panel, 114);
    lv_obj_set_align(ui_Ideal_Temp_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Ideal_Temp_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ideal_Temp_Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Ideal_Temp_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ideal_Temp_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ideal_Temp_Value, -24);
    lv_obj_set_y(ui_Ideal_Temp_Value, 113);
    lv_obj_set_align(ui_Ideal_Temp_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ideal_Temp_Value, "10");

    ui_Fan_Speed_Slider = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_Fan_Speed_Slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Fan_Speed_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Fan_Speed_Slider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_Fan_Speed_Slider, 86);
    lv_obj_set_height(ui_Fan_Speed_Slider, 10);
    lv_obj_set_x(ui_Fan_Speed_Slider, -12);
    lv_obj_set_y(ui_Fan_Speed_Slider, 67);
    lv_obj_set_align(ui_Fan_Speed_Slider, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Setpoint_Down, ui_event_Setpoint_Down, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setpoint_Up, ui_event_Setpoint_Up, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ideal_Temp_Slider, ui_event_Ideal_Temp_Slider, LV_EVENT_ALL, NULL);
    uic_Power = ui_Power;
    uic_Menu = ui_Menu;
    uic_Burnt_Toast = ui_Burnt_Toast;
    uic_Setpoint_Down = ui_Setpoint_Down;
    uic_Setpoint_Up = ui_Setpoint_Up;
    uic_Time_Panel = ui_Time_Panel;
    uic_Time_Value = ui_Time_Value;
    uic_Ideal_Temp_lable = ui_Ideal_Temp_lable;
    uic_Fan_Speed_Value = ui_Fan_Speed_Value;
    uic_Roof_Humidity_Panel = ui_Roof_Humidity_Panel;
    uic_Roof_Temp_Panel = ui_Roof_Temp_Panel;
    uic_Roof_Temp_Symbol = ui_Roof_Temp_Symbol;
    uic_Roof_Humidity_Symbol = ui_Roof_Humidity_Symbol;
    uic_House_Temp_Panel = ui_House_Temp_Panel;
    uic_House_Humidity_Panel = ui_House_Humidity_Panel;
    uic_House_Humidity_Symbol = ui_House_Humidity_Symbol;
    uic_House_Temp_Value = ui_House_Temp_Value;
    uic_House_Humidity_Value = ui_House_Humidity_Value;
    uic_Roof_Temp_Value = ui_Roof_Temp_Value;
    uic_Roof_Humidity_Value = ui_Roof_Humidity_Value;
    uic_Filter_Life_panel = ui_Filter_Life_panel;
    uic_Filter_Life_Lable = ui_Filter_Life_Lable;
    uic_Filter_Life_Value = ui_Filter_Life_Value;
    uic_Ideal_Temp_Slider = ui_Ideal_Temp_Slider;
    uic_Ideal_Temp_Panel = ui_Ideal_Temp_Panel;
    uic_Ideal_Temp_Value = ui_Ideal_Temp_Value;
    uic_Fan_Speed_Slider = ui_Fan_Speed_Slider;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_Power = NULL;
    ui_Power = NULL;
    uic_Menu = NULL;
    ui_Menu = NULL;
    uic_Burnt_Toast = NULL;
    ui_Burnt_Toast = NULL;
    uic_Setpoint_Down = NULL;
    ui_Setpoint_Down = NULL;
    uic_Setpoint_Up = NULL;
    ui_Setpoint_Up = NULL;
    uic_Time_Panel = NULL;
    ui_Time_Panel = NULL;
    uic_Time_Value = NULL;
    ui_Time_Value = NULL;
    uic_Ideal_Temp_lable = NULL;
    ui_Ideal_Temp_lable = NULL;
    ui_Fan_Speed_Panel = NULL;
    ui_Fan_Speed_Lable = NULL;
    uic_Fan_Speed_Value = NULL;
    ui_Fan_Speed_Value = NULL;
    uic_Roof_Humidity_Panel = NULL;
    ui_Roof_Humidity_Panel = NULL;
    uic_Roof_Temp_Panel = NULL;
    ui_Roof_Temp_Panel = NULL;
    uic_Roof_Temp_Symbol = NULL;
    ui_Roof_Temp_Symbol = NULL;
    uic_Roof_Humidity_Symbol = NULL;
    ui_Roof_Humidity_Symbol = NULL;
    uic_House_Temp_Panel = NULL;
    ui_House_Temp_Panel = NULL;
    uic_House_Humidity_Panel = NULL;
    ui_House_Humidity_Panel = NULL;
    ui_House_Temp_Symbol = NULL;
    uic_House_Humidity_Symbol = NULL;
    ui_House_Humidity_Symbol = NULL;
    uic_House_Temp_Value = NULL;
    ui_House_Temp_Value = NULL;
    uic_House_Humidity_Value = NULL;
    ui_House_Humidity_Value = NULL;
    uic_Roof_Temp_Value = NULL;
    ui_Roof_Temp_Value = NULL;
    uic_Roof_Humidity_Value = NULL;
    ui_Roof_Humidity_Value = NULL;
    uic_Filter_Life_panel = NULL;
    ui_Filter_Life_panel = NULL;
    uic_Filter_Life_Lable = NULL;
    ui_Filter_Life_Lable = NULL;
    uic_Filter_Life_Value = NULL;
    ui_Filter_Life_Value = NULL;
    uic_Ideal_Temp_Slider = NULL;
    ui_Ideal_Temp_Slider = NULL;
    uic_Ideal_Temp_Panel = NULL;
    ui_Ideal_Temp_Panel = NULL;
    uic_Ideal_Temp_Value = NULL;
    ui_Ideal_Temp_Value = NULL;
    uic_Fan_Speed_Slider = NULL;
    ui_Fan_Speed_Slider = NULL;

}
