// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Power;
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_Burnt_Toast;
extern void ui_event_Setpoint_Down(lv_event_t * e);
extern lv_obj_t * ui_Setpoint_Down;
extern void ui_event_Setpoint_Up(lv_event_t * e);
extern lv_obj_t * ui_Setpoint_Up;
extern lv_obj_t * ui_Time_Panel;
extern lv_obj_t * ui_Time_Value;
extern lv_obj_t * ui_Ideal_Temp_lable;
extern lv_obj_t * ui_Fan_Speed_Panel;
extern lv_obj_t * ui_Fan_Speed_Lable;
extern lv_obj_t * ui_Fan_Speed_Value;
extern lv_obj_t * ui_Roof_Humidity_Panel;
extern lv_obj_t * ui_Roof_Temp_Panel;
extern lv_obj_t * ui_Roof_Temp_Symbol;
extern lv_obj_t * ui_Roof_Humidity_Symbol;
extern lv_obj_t * ui_House_Temp_Panel;
extern lv_obj_t * ui_House_Humidity_Panel;
extern lv_obj_t * ui_House_Temp_Symbol;
extern lv_obj_t * ui_House_Humidity_Symbol;
extern lv_obj_t * ui_House_Temp_Value;
extern lv_obj_t * ui_House_Humidity_Value;
extern lv_obj_t * ui_Roof_Temp_Value;
extern lv_obj_t * ui_Roof_Humidity_Value;
extern lv_obj_t * ui_Filter_Life_panel;
extern lv_obj_t * ui_Filter_Life_Lable;
extern lv_obj_t * ui_Filter_Life_Value;
extern void ui_event_Ideal_Temp_Slider(lv_event_t * e);
extern lv_obj_t * ui_Ideal_Temp_Slider;
extern lv_obj_t * ui_Ideal_Temp_Panel;
extern lv_obj_t * ui_Ideal_Temp_Value;
extern lv_obj_t * ui_Fan_Speed_Slider;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Power;
extern lv_obj_t * uic_Menu;
extern lv_obj_t * uic_Burnt_Toast;
extern lv_obj_t * uic_Setpoint_Down;
extern lv_obj_t * uic_Setpoint_Up;
extern lv_obj_t * uic_Time_Panel;
extern lv_obj_t * uic_Time_Value;
extern lv_obj_t * uic_Ideal_Temp_lable;
extern lv_obj_t * uic_Fan_Speed_Value;
extern lv_obj_t * uic_Roof_Humidity_Panel;
extern lv_obj_t * uic_Roof_Temp_Panel;
extern lv_obj_t * uic_Roof_Temp_Symbol;
extern lv_obj_t * uic_Roof_Humidity_Symbol;
extern lv_obj_t * uic_House_Temp_Panel;
extern lv_obj_t * uic_House_Humidity_Panel;
extern lv_obj_t * uic_House_Humidity_Symbol;
extern lv_obj_t * uic_House_Temp_Value;
extern lv_obj_t * uic_House_Humidity_Value;
extern lv_obj_t * uic_Roof_Temp_Value;
extern lv_obj_t * uic_Roof_Humidity_Value;
extern lv_obj_t * uic_Filter_Life_panel;
extern lv_obj_t * uic_Filter_Life_Lable;
extern lv_obj_t * uic_Filter_Life_Value;
extern lv_obj_t * uic_Ideal_Temp_Slider;
extern lv_obj_t * uic_Ideal_Temp_Panel;
extern lv_obj_t * uic_Ideal_Temp_Value;
extern lv_obj_t * uic_Fan_Speed_Slider;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

