// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: New Button Testing

#ifndef _UI_COMP_POWER_H
#define _UI_COMP_POWER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Power
#define UI_COMP_POWER_POWER 0
#define _UI_COMP_POWER_NUM 1
lv_obj_t * ui_Power_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
