// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: New Button Testing

#include "ui.h"

lv_obj_t * uic_Menu_Lable_Screen_2;
lv_obj_t * uic_Menu_Screen_2;
lv_obj_t * uic_Screen_2;
lv_obj_t * ui_Screen_2 = NULL;
lv_obj_t * ui_Menu_Screen_2 = NULL;
lv_obj_t * ui_Menu_Lable_Screen_2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Switch4 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions
void ui_event_Menu_Screen_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Menu, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        _ui_screen_change(&ui_Screen_1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_1_screen_init);
    }
}

// build funtions

void ui_Screen_2_screen_init(void)
{
    ui_Screen_2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_2, lv_color_hex(0x788EF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Screen_2 = lv_obj_create(ui_Screen_2);
    lv_obj_remove_style_all(ui_Menu_Screen_2);
    lv_obj_set_width(ui_Menu_Screen_2, 62);
    lv_obj_set_height(ui_Menu_Screen_2, 39);
    lv_obj_set_x(ui_Menu_Screen_2, 81);
    lv_obj_set_y(ui_Menu_Screen_2, -134);
    lv_obj_set_align(ui_Menu_Screen_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Menu_Screen_2, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Menu_Screen_2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Menu_Screen_2, lv_color_hex(0x19C31A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu_Screen_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu_Screen_2, lv_color_hex(0xF21212), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Menu_Screen_2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_Menu_Screen_2, 50, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Menu_Lable_Screen_2 = lv_label_create(ui_Screen_2);
    lv_obj_set_width(ui_Menu_Lable_Screen_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Menu_Lable_Screen_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Menu_Lable_Screen_2, 81);
    lv_obj_set_y(ui_Menu_Lable_Screen_2, -134);
    lv_obj_set_align(ui_Menu_Lable_Screen_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Menu_Lable_Screen_2, "Menu");
    lv_obj_clear_flag(ui_Menu_Lable_Screen_2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Menu_Lable_Screen_2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen_2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 100);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_x(ui_Container2, -59);
    lv_obj_set_y(ui_Container2, -128);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen_2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 100);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, -59);
    lv_obj_set_y(ui_Container1, -9);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen_2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 100);
    lv_obj_set_height(ui_Container3, 50);
    lv_obj_set_x(ui_Container3, -59);
    lv_obj_set_y(ui_Container3, -69);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Screen_2);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 100);
    lv_obj_set_height(ui_Container4, 50);
    lv_obj_set_x(ui_Container4, -60);
    lv_obj_set_y(ui_Container4, 51);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen_2);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 78);
    lv_obj_set_y(ui_Switch1, -83);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x18F223), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Screen_2);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 78);
    lv_obj_set_y(ui_Switch2, -39);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x1BE615), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Screen_2);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 78);
    lv_obj_set_y(ui_Switch3, 9);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x15EA2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_Screen_2);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, 77);
    lv_obj_set_y(ui_Switch4, 54);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x17E943), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen_2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -64);
    lv_obj_set_y(ui_Label7, -128);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Settings");

    ui_Label8 = lv_label_create(ui_Screen_2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -64);
    lv_obj_set_y(ui_Label8, -69);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Wifi");

    ui_Label9 = lv_label_create(ui_Screen_2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -64);
    lv_obj_set_y(ui_Label9, -10);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "MQTT");

    ui_Label11 = lv_label_create(ui_Screen_2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -67);
    lv_obj_set_y(ui_Label11, 52);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Hassio");

    ui_Keyboard1 = lv_keyboard_create(ui_Screen_2);
    lv_obj_set_width(ui_Keyboard1, 236);
    lv_obj_set_height(ui_Keyboard1, 74);
    lv_obj_set_x(ui_Keyboard1, 1);
    lv_obj_set_y(ui_Keyboard1, 121);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Menu_Screen_2, ui_event_Menu_Screen_2, LV_EVENT_ALL, NULL);
    uic_Screen_2 = ui_Screen_2;
    uic_Menu_Screen_2 = ui_Menu_Screen_2;
    uic_Menu_Lable_Screen_2 = ui_Menu_Lable_Screen_2;

}

void ui_Screen_2_screen_destroy(void)
{
    if(ui_Screen_2) lv_obj_del(ui_Screen_2);

    // NULL screen variables
    uic_Screen_2 = NULL;
    ui_Screen_2 = NULL;
    uic_Menu_Screen_2 = NULL;
    ui_Menu_Screen_2 = NULL;
    uic_Menu_Lable_Screen_2 = NULL;
    ui_Menu_Lable_Screen_2 = NULL;
    ui_Container2 = NULL;
    ui_Container1 = NULL;
    ui_Container3 = NULL;
    ui_Container4 = NULL;
    ui_Switch1 = NULL;
    ui_Switch2 = NULL;
    ui_Switch3 = NULL;
    ui_Switch4 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Label11 = NULL;
    ui_Keyboard1 = NULL;

}
